# Generated by Django 5.1.6 on 2025-03-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickingList',
            fields=[
                ('picking_list_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warehouse_id', models.CharField(blank=True, max_length=255, null=True)),
                ('picked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('picked_status', models.TextField(blank=True, null=True)),
                ('picked_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'picking_list',
                'managed': False,
            },
        ),
    ]
