# Generated by Django 5.1.6 on 2025-03-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('del_order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('order_status', models.TextField(blank=True, null=True)),
                ('content_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_project_based', models.TextField(blank=True, null=True)),
                ('is_partial_delivery', models.TextField(blank=True, null=True)),
                ('service_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_transfer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('del_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogisticsApprovalRequest',
            fields=[
                ('approval_request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('approval_status', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'logistics_approval_request',
                'managed': False,
            },
        ),
    ]
